/**
 * Markdown export — materializes approved memories from the DB to disk.
 *
 * The DB is the system of record; this regenerates a human-readable mirror
 * under capture.export_dir (a Nexus-owned sandbox, default
 * ~/.claude/memories/exports). Deliberately NOT ~/.claude/projects/<project>/memory:
 * that directory is auto-loaded in full by Claude Code's own native
 * auto-memory feature at every session start, which would duplicate and
 * conflict with prompt-runner's per-prompt relevance-floored recall.
 */

import { mkdirSync, writeFileSync, readFileSync, readdirSync, rmSync, existsSync } from 'fs';
import { join } from 'path';
import Database from 'better-sqlite3';
import { stringify as yamlStringify } from 'yaml';
import { getNexusConfig } from '../core/config.js';
import { effectiveConfidence } from '../core/decay.js';
import type { Memory } from '../core/types.js';

export interface ExportResult {
  buckets: number;
  files: number;
  dir: string;
}

export interface ExportOptions {
  /**
   * IDs of memories inserted/merged by the caller's own operation. When set,
   * only these memories' files are (unconditionally) written and only their
   * bucket indexes are rebuilt — no directory listing, no disk read of
   * unrelated memories, no orphan-bucket pruning. Use for the per-session
   * capture hot path; omit for a full resync (CLI export, backfill, migrate).
   */
  touchedIds?: string[];
}

function slug(s: string): string {
  return s.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/^-+|-+$/g, '').slice(0, 48) || 'memory';
}

function rowToMemory(r: Record<string, unknown>): Memory {
  return { ...(r as unknown as Memory), tags: JSON.parse((r.tags as string) || '[]') };
}

function bucketOf(project: string | null): string {
  return project || '_global';
}

function memoryFileName(m: Memory): string {
  return `${m.id}-${slug(m.title)}.md`;
}

function memoryFileContent(m: Memory): string {
  const frontmatter = yamlStringify({
    id: m.id,
    memory_type: m.memory_type,
    scope: m.scope,
    project: m.project,
    confidence: m.confidence,
    decay_class: m.decay_class,
    tags: m.tags,
    source_session: m.source_session_id,
    created_at: m.created_at,
    last_verified_at: m.last_verified_at,
  }).trim();
  return `---\n${frontmatter}\n---\n\n# ${m.title}\n\n${m.body}\n`;
}

/** Builds the MEMORY.md index body for one bucket's approved, non-superseded memories. */
function buildIndexContent(bucket: string, mems: Memory[], cap: number): string {
  // Sort by decay rank desc so the index always shows the most-relevant memories.
  // Use stable sort: ties preserved in SQL-fetch order (memory_type, confidence DESC, title).
  const sorted = [...mems].sort((a, b) => effectiveConfidence(b) - effectiveConfidence(a));
  const totalCount = sorted.length;
  const topMems = sorted.slice(0, cap);

  const byType = new Map<string, { title: string; file: string; hook: string }[]>();
  for (const m of topMems) {
    const hook = m.body.split('\n')[0].slice(0, 100);
    if (!byType.has(m.memory_type)) byType.set(m.memory_type, []);
    byType.get(m.memory_type)!.push({ title: m.title, file: memoryFileName(m), hook });
  }

  const index: string[] = [`# Memory — ${bucket}`, '', `_${totalCount} memories · generated by Claude Nexus_`, ''];
  for (const [type, items] of [...byType.entries()].sort()) {
    index.push(`## ${type}`, '');
    for (const it of items) {
      index.push(`- [${it.title}](${it.file}) — ${it.hook}`);
    }
    index.push('');
  }
  if (totalCount > cap) {
    index.push(`> … ${totalCount - cap} more memories — use nexus_search to retrieve them.`);
  }
  return index.join('\n');
}

function approvedMemoriesInBucket(db: Database.Database, bucket: string): Memory[] {
  const rows = bucket === '_global'
    ? db.prepare(`
        SELECT * FROM memories
        WHERE review_status = 'approved' AND superseded_by IS NULL AND project IS NULL
        ORDER BY memory_type, confidence DESC, title
      `).all() as Record<string, unknown>[]
    : db.prepare(`
        SELECT * FROM memories
        WHERE review_status = 'approved' AND superseded_by IS NULL AND project = ?
        ORDER BY memory_type, confidence DESC, title
      `).all(bucket) as Record<string, unknown>[];
  return rows.map(rowToMemory);
}

/**
 * Writes only the memories named by touchedIds and rebuilds their buckets'
 * indexes from the DB. No directory listing, no disk reads, no pruning —
 * the hot path for per-session capture, where the caller already knows
 * exactly which memories changed.
 */
function exportTouched(db: Database.Database, exportDir: string, cap: number, touchedIds: string[]): ExportResult {
  const placeholders = touchedIds.map(() => '?').join(',');
  const touchedRows = db.prepare(`SELECT * FROM memories WHERE id IN (${placeholders})`).all(...touchedIds) as Record<string, unknown>[];

  const buckets = new Set<string>();
  let files = 0;
  for (const r of touchedRows) {
    const mem = rowToMemory(r);
    const bucket = bucketOf(mem.project);
    buckets.add(bucket);
    const fpath = join(exportDir, bucket, 'memory', memoryFileName(mem));
    if (mem.review_status !== 'approved' || mem.superseded_by) {
      // No longer live (rejected/superseded) — remove a previously-exported
      // file if one exists. Single existence check, no directory listing.
      if (existsSync(fpath)) rmSync(fpath);
      continue;
    }
    mkdirSync(join(exportDir, bucket, 'memory'), { recursive: true });
    writeFileSync(fpath, memoryFileContent(mem));
    files++;
  }

  let processedBuckets = 0;
  for (const bucket of buckets) {
    const mems = approvedMemoriesInBucket(db, bucket);
    if (mems.length === 0) continue;
    const dir = join(exportDir, bucket, 'memory');
    mkdirSync(dir, { recursive: true });
    writeFileSync(join(dir, 'MEMORY.md'), buildIndexContent(bucket, mems, cap));
    processedBuckets++;
  }

  return { buckets: processedBuckets, files, dir: exportDir };
}

/**
 * Export every approved, non-superseded memory to capture.export_dir.
 * One subdir per project (global/shared memories go to `_global`), each with
 * a MEMORY.md index and one file per memory. Stale .md files are pruned.
 *
 * Full mode (no touchedIds) only fills in missing files — it never rewrites
 * an existing memory file, since nothing else keeps the mirror in sync with
 * in-place edits (consolidate/distill/dashboard edits don't call this), so a
 * content diff here would just be reads that never fire in practice.
 */
export function exportAll(db: Database.Database, exportDirOverride?: string, options?: ExportOptions): ExportResult {
  const cfg = getNexusConfig();
  const exportDir = exportDirOverride ?? cfg.capture.export_dir;
  const cap = cfg.capture.memory_md_max_items ?? 200;

  if (options?.touchedIds && options.touchedIds.length > 0) {
    return exportTouched(db, exportDir, cap, options.touchedIds);
  }

  const rows = db.prepare(`
    SELECT * FROM memories
    WHERE review_status = 'approved' AND superseded_by IS NULL
    ORDER BY memory_type, confidence DESC, title
  `).all() as Record<string, unknown>[];

  const byBucket = new Map<string, Memory[]>();
  for (const r of rows) {
    const mem = rowToMemory(r);
    const bucket = bucketOf(mem.project);
    if (!byBucket.has(bucket)) byBucket.set(bucket, []);
    byBucket.get(bucket)!.push(mem);
  }

  let files = 0;
  for (const [bucket, mems] of byBucket) {
    const dir = join(exportDir, bucket, 'memory');
    mkdirSync(dir, { recursive: true });

    const expected = new Set(['MEMORY.md']);
    for (const m of mems) {
      const fname = memoryFileName(m);
      expected.add(fname);
      const fpath = join(dir, fname);
      // Existence check only: nothing else keeps files in sync with in-place
      // edits, so a missing file always means "never exported" — fill it in.
      if (!existsSync(fpath)) {
        writeFileSync(fpath, memoryFileContent(m));
        files++;
      }
    }

    // Remove only files no longer backed by a live memory in this bucket.
    for (const f of readdirSync(dir)) {
      if (f.endsWith('.md') && !expected.has(f)) rmSync(join(dir, f));
    }

    writeFileSync(join(dir, 'MEMORY.md'), buildIndexContent(bucket, mems, cap));
    files++;
  }

  // Prune project directories whose memory/ export Nexus wrote previously but
  // which no longer correspond to any live bucket (project renamed, merged via
  // project_aliases, or the memory entirely removed). Only ever deletes the
  // memory/ subdir Nexus owns — a sibling .jsonl session file (Claude Code's
  // own data) always survives, and the parent dir is removed only once empty.
  if (existsSync(exportDir)) {
    for (const entry of readdirSync(exportDir, { withFileTypes: true })) {
      if (!entry.isDirectory() || byBucket.has(entry.name)) continue;
      const projectDir = join(exportDir, entry.name);
      const memDir = join(projectDir, 'memory');
      if (!existsSync(memDir)) continue;

      rmSync(memDir, { recursive: true, force: true });
      if (readdirSync(projectDir).length === 0) {
        rmSync(projectDir, { recursive: true, force: true });
      }
    }
  }

  return { buckets: byBucket.size, files, dir: exportDir };
}
