/**
 * Markdown export — materializes approved memories from the DB to disk.
 *
 * The DB is the system of record; this regenerates a human-readable mirror
 * under capture.export_dir (a Nexus-owned sandbox, default
 * ~/.claude/memories/exports). Deliberately NOT ~/.claude/projects/<project>/memory:
 * that directory is auto-loaded in full by Claude Code's own native
 * auto-memory feature at every session start, which would duplicate and
 * conflict with prompt-runner's per-prompt relevance-floored recall.
 */

import { mkdirSync, writeFileSync, readFileSync, readdirSync, rmSync, existsSync } from 'fs';
import { join } from 'path';
import Database from 'better-sqlite3';
import { stringify as yamlStringify } from 'yaml';
import { getNexusConfig } from '../core/config.js';
import { effectiveConfidence } from '../core/decay.js';
import type { Memory } from '../core/types.js';

export interface ExportResult {
  buckets: number;
  files: number;
  dir: string;
}

function slug(s: string): string {
  return s.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/^-+|-+$/g, '').slice(0, 48) || 'memory';
}

function rowToMemory(r: Record<string, unknown>): Memory {
  return { ...(r as unknown as Memory), tags: JSON.parse((r.tags as string) || '[]') };
}

/**
 * Export every approved, non-superseded memory to capture.export_dir.
 * One subdir per project (global/shared memories go to `_global`), each with
 * a MEMORY.md index and one file per memory. Stale .md files are pruned.
 */
export function exportAll(db: Database.Database, exportDirOverride?: string): ExportResult {
  const cfg = getNexusConfig();
  const exportDir = exportDirOverride ?? cfg.capture.export_dir;
  const cap = cfg.capture.memory_md_max_items ?? 200;

  const rows = db.prepare(`
    SELECT * FROM memories
    WHERE review_status = 'approved' AND superseded_by IS NULL
    ORDER BY memory_type, confidence DESC, title
  `).all() as Record<string, unknown>[];

  const byBucket = new Map<string, Memory[]>();
  for (const r of rows) {
    const mem = rowToMemory(r);
    const bucket = mem.project || '_global';
    if (!byBucket.has(bucket)) byBucket.set(bucket, []);
    byBucket.get(bucket)!.push(mem);
  }

  let files = 0;
  for (const [bucket, mems] of byBucket) {
    const dir = join(exportDir, bucket, 'memory');
    mkdirSync(dir, { recursive: true });

    // Sort by decay rank desc so the index always shows the most-relevant memories.
    // Use stable sort: ties preserved in SQL-fetch order (memory_type, confidence DESC, title).
    const sorted = [...mems].sort((a, b) => effectiveConfidence(b) - effectiveConfidence(a));
    const totalCount = sorted.length;
    const topMems = sorted.slice(0, cap);

    const byType = new Map<string, { title: string; file: string; hook: string }[]>();
    const expected = new Set(['MEMORY.md']);

    for (const m of mems) {
      const fname = `${m.id}-${slug(m.title)}.md`;
      expected.add(fname);
      const frontmatter = yamlStringify({
        id: m.id,
        memory_type: m.memory_type,
        scope: m.scope,
        project: m.project,
        confidence: m.confidence,
        decay_class: m.decay_class,
        tags: m.tags,
        source_session: m.source_session_id,
        created_at: m.created_at,
        last_verified_at: m.last_verified_at,
      }).trim();

      const content = `---\n${frontmatter}\n---\n\n# ${m.title}\n\n${m.body}\n`;
      const fpath = join(dir, fname);
      // Skip the write if content is unchanged, to avoid needless mtime/git churn.
      if (!existsSync(fpath) || readFileSync(fpath, 'utf-8') !== content) {
        writeFileSync(fpath, content);
        files++;
      }
    }

    // Remove only files no longer backed by a live memory in this bucket.
    for (const f of readdirSync(dir)) {
      if (f.endsWith('.md') && !expected.has(f)) rmSync(join(dir, f));
    }

    // Build index from top-N only
    for (const m of topMems) {
      const fname = `${m.id}-${slug(m.title)}.md`;
      const hook = m.body.split('\n')[0].slice(0, 100);
      if (!byType.has(m.memory_type)) byType.set(m.memory_type, []);
      byType.get(m.memory_type)!.push({ title: m.title, file: fname, hook });
    }

    const index: string[] = [`# Memory — ${bucket}`, '', `_${totalCount} memories · generated by Claude Nexus_`, ''];
    for (const [type, items] of [...byType.entries()].sort()) {
      index.push(`## ${type}`, '');
      for (const it of items) {
        index.push(`- [${it.title}](${it.file}) — ${it.hook}`);
      }
      index.push('');
    }
    if (totalCount > cap) {
      index.push(`> … ${totalCount - cap} more memories — use nexus_search to retrieve them.`);
    }
    const indexContent = index.join('\n');
    const indexPath = join(dir, 'MEMORY.md');
    if (!existsSync(indexPath) || readFileSync(indexPath, 'utf-8') !== indexContent) {
      writeFileSync(indexPath, indexContent);
      files++;
    }
  }

  // Prune project directories whose memory/ export Nexus wrote previously but
  // which no longer correspond to any live bucket (project renamed, merged via
  // project_aliases, or the memory entirely removed). Only ever deletes the
  // memory/ subdir Nexus owns — a sibling .jsonl session file (Claude Code's
  // own data) always survives, and the parent dir is removed only once empty.
  if (existsSync(exportDir)) {
    for (const entry of readdirSync(exportDir, { withFileTypes: true })) {
      if (!entry.isDirectory() || byBucket.has(entry.name)) continue;
      const projectDir = join(exportDir, entry.name);
      const memDir = join(projectDir, 'memory');
      if (!existsSync(memDir)) continue;

      rmSync(memDir, { recursive: true, force: true });
      if (readdirSync(projectDir).length === 0) {
        rmSync(projectDir, { recursive: true, force: true });
      }
    }
  }

  return { buckets: byBucket.size, files, dir: exportDir };
}
